version: '2'
services:
  covid19stats-app:
    image: covid19stats
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://covid19stats-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=covid19stats
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://covid19stats-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://covid19stats-elasticsearch:9200
    ports:
      - 8080:8080
  covid19stats-mongodb:
    extends:
      file: mongodb.yml
      service: covid19stats-mongodb
  covid19stats-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: covid19stats-elasticsearch
